name: Initial Setup

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_initial_setup:
    runs-on: ubuntu-latest

    steps:
       - name: Install dependencies
         run: |
            source /home/milky/Envs/n1_scraper/bin/activate
            pip install -r /home/milky/N1Scraper/requirements.txt

       - name: Create data directories
         run: |
            mkdir -p /home/milky/N1Scraper/data_temp

       - name: Run scraper script
         run: python /home/milky/N1Scraper/scraper/initialize_data.py

       - name: Echo job status
         run: echo "Daily scraper job status is ${{ job.status }}."

       - name: Push to GH
         run: | 
            cd /home/milky/N1Scraper/
            git config url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com
            git pull origin main
            git add data/articles.db data/last_scraped_datetime.txt data/duplicates.json 
            git commit -m "data_update"
            git push origin main
